# Generated by Django 4.1.3 on 2022-12-02 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ARTICLE', 'Запись'), ('PAGE', 'Страница')], default='PAGE', max_length=50, verbose_name='Тип страницы')),
                ('title', models.CharField(max_length=80, null=True, verbose_name='Название')),
                ('preview_text', models.CharField(blank=True, help_text='Краткое описание не более 50 символов', max_length=150, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Содержание')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Создана')),
                ('date_change', models.DateTimeField(auto_now_add=True, verbose_name='Отредактирована')),
                ('url_path', models.SlugField(help_text='Путь к странице', null=True, unique=True, verbose_name='url')),
                ('creator', models.ForeignKey(help_text='Пользователь создал', on_delete=django.db.models.deletion.CASCADE, related_name='correctUser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': ('Страница',),
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='PicturiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(max_length=80, upload_to='cvresume-web/files/pictures/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(help_text='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Путь к img',
                'verbose_name_plural': 'Путь к изображениям',
            },
        ),
        migrations.CreateModel(
            name='WorkExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_data', models.DateField(help_text='Дата начала обучения', verbose_name='Начало обучения')),
                ('complated_data', models.DateField(blank=True, help_text='Дата окончания обучения', verbose_name='Окончание учёбы')),
                ('public', models.TextField(choices=[('PUBLIC', 'Публикация'), ('NOPUBLIC', '----')], default='NOPUBLIC', help_text='Публикуем на странице или нет. По умолчанию, публикации нет', verbose_name='Публикация')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namePositionsMenu', to='apps.pagesmodel', verbose_name='Должность')),
                ('preview_text', models.ForeignKey(blank=True, help_text='Краткое описание в 80 символов', on_delete=django.db.models.deletion.CASCADE, related_name='previewPositionsMenu', to='apps.pagesmodel', verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Дата работы',
                'verbose_name_plural': 'Опыт работ',
            },
        ),
        migrations.CreateModel(
            name='MiddlePicturiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgPages', to='apps.pagesmodel')),
                ('pathPictiries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgPath', to='apps.picturiesmodel')),
            ],
            options={
                'verbose_name': 'Изображение не странице',
                'verbose_name_plural': 'Изображения страницы',
            },
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_page', models.TextField(choices=[('PARENTS', 'Родительский'), ('CHILDE', 'Дочернеий')], default='PARENTS', max_length=50)),
                ('public', models.TextField(choices=[('PUBLIC', 'Публикация'), ('NOPUBLIC', '----')], default='NOPUBLIC', help_text='Публикуем на странице или нет. По умолчанию, публикации нет', verbose_name='Публикация')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagesChild', to='apps.pagesmodel')),
            ],
            options={
                'verbose_name': 'Раздел меню',
                'verbose_name_plural': 'Разделы меню',
            },
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_data', models.DateField(help_text='Начало работы в должности', verbose_name='Начало работы')),
                ('complated_data', models.DateField(blank=True, help_text='Окончание работы')),
                ('public', models.TextField(choices=[('PUBLIC', 'Публикация'), ('NOPUBLIC', '----')], default='NOPUBLIC', help_text='Публикуем на странице или нет. По умолчанию, публикации нет', verbose_name='Публикация')),
                ('preview_text', models.ForeignKey(blank=True, help_text='Краткое описание в 80 символов', on_delete=django.db.models.deletion.CASCADE, related_name='previewPositionsMenuExpe', to='apps.pagesmodel', verbose_name='Краткое описание')),
                ('title', models.ForeignKey(help_text='Наименование курса', on_delete=django.db.models.deletion.CASCADE, related_name='titlePositionsMenuExpe', to='apps.pagesmodel')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
    ]
