# Generated by Django 4.1.3 on 2022-11-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesmodel',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='picturiesmodel',
            name='path',
            field=models.ImageField(max_length=80, upload_to='cvresume-web/files/pictures/%Y/%m/%d/'),
        ),
    ]
