# Generated by Django 4.1.3 on 2022-12-01 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationmodel',
            options={'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.RemoveField(
            model_name='educationmodel',
            name='delete',
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='preview_text',
            field=models.TextField(blank=True, help_text='Превью описание', max_length=80, verbose_name='Краткое описание в 80 символов'),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='public',
            field=models.TextField(choices=[('PUBLIC', 'Публикация'), ('NOPUBLIC', '----')], default='NOPUBLIC', help_text='Публикуем на странице или нет. По умолчанию, публикации нет', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='title',
            field=models.ForeignKey(help_text='Наименование курса', on_delete=django.db.models.deletion.CASCADE, to='apps.pagesmodel'),
        ),
        migrations.AlterField(
            model_name='workexperiencemodel',
            name='preview_text',
            field=models.TextField(blank=True, help_text='Превью описание', max_length=80),
        ),
        migrations.AlterField(
            model_name='workexperiencemodel',
            name='public',
            field=models.TextField(choices=[('PUBLIC', 'Публикация'), ('NOPUBLIC', '----')], default='NOPUBLIC', help_text='Публикуем на странице или нет. По умолчанию, публикации нет', verbose_name='Публикация'),
        ),
    ]
