# Generated by Django 4.1.3 on 2022-12-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_educationmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menumodel',
            old_name='id_pages',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='menumodel',
            name='delete',
        ),
        migrations.AddField(
            model_name='menumodel',
            name='public',
            field=models.TextField(choices=[('PUBLIC', 'Публикация'), ('NOPUBLIC', '----')], default='NOPUBLIC', help_text='Публикуем на странице или нет. По умолчанию, публикации нет', verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='preview_text',
            field=models.TextField(blank=True, help_text='Краткое описание в 80 символов', max_length=80, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='pagesmodel',
            name='url_path',
            field=models.SlugField(help_text='Путь к странице', null=True, unique=True, verbose_name='url'),
        ),
    ]
