# Generated by Django 4.1.3 on 2022-11-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_pagesmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='delete',
            field=models.BooleanField(null=True, verbose_name='Удалить'),
        ),
        migrations.AddField(
            model_name='workexperiencemodel',
            name='delete',
            field=models.BooleanField(null=True, verbose_name='Удалить'),
        ),
    ]
