# Generated by Django 4.1.3 on 2022-11-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_middlepages_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='middlepages',
            name='education',
            field=models.ForeignKey(default='Null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educationMainPage', to='apps.educationmodel'),
        ),
        migrations.AlterField(
            model_name='middlepages',
            name='experience',
            field=models.ForeignKey(default='Null', help_text='Превью описания опыта и краткое описание \n3\n\t\t          из базовой страницы. Свойство - НЕ ОБЯЗАТЕЛЬНО', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experienceMainPage', to='apps.workexperiencemodel'),
        ),
    ]
